version: '2.4'
services:
    microservice:
        container_name: microservice
        image: '{DOCKER_IMAGE}'
        ports:
        - '9999:9999'
        logging:
            driver: "json-file"
            options:
                max-file: '3'
                max-size: '50m'
        cpus: 1
        mem_limit: 1gb
        network_mode: bridge
        environment: 
            - NODE_ENV=development
        ulimits:
            core: 0
        restart: unless-stopped